---
version: '3.9'
services:
  todo-list:
    build:
      context: .
      dockerfile: Production.dockerfile
      args:
        CERT_FILE_PATH: cert.pem
        PRIVKEY_FILE_PATH: cert_priv.pem
        DB_INITDB: ${DB_INITDB}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: 5432  # Default port of postgres
        DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT}:8080'

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_INITDB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: {}
