---
version: '3.9'
services:
  todo-list:
    build:
      context: .
      dockerfile: Production.dockerfile
      args:
        CERT_FILE_PATH: cert.pem
        PRIVKEY_FILE_PATH: cert_priv.pem
    ports:
      - '${PORT}:8080'